file-path: /data/pic
jasypt:
  encryptor:
    password: tsingtec1218
spring:
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

  #数据库操作
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/malum?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: ENC(qxkgqjXH/jeft8KzO3EywA==)
    password: ENC(IrMnoCs9L9jxtYCvckf5Rg==)

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: com.tsingtec.mini.utils.MySQLDialectUTF8
      hibernate.format_sql: false
      hibernate:
        enable_lazy_load_no_trans: true
    open-in-view: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: file:${file-path},classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/
#七牛
qiniu:
  accessKey: 91Wg1ATQdNrU3z4kX3YQ0M859ijYX6WjXXnq1G1t
  secretKey: dhCyPv2OujzF15fNqxzTISsdzClkfxVcSJnsm6OR
  bucket: grid-img
  path: http://gridpic.tsing-tec.com

swagger2:
  enable: true

wx:
  miniapp:
    configs:
      - appId: wxffbd431d1affeacc
        secret: 12d1145f4e19a3c26ec4f206da42ec89
        token: tsingtec1218
        aesKey: LqKwCf1MfwMvPOLlt5GYFn7lDCV2Jw4wIpQLqwboVay
        msgDataFormat: JSON
  mp:
    configs:
      - appId: wxa81090b89053b016
        secret: 517dfee6e4d72f490364333a2925707e
        token: tsingtec1218
        aesKey: LqKwCf1MfwMvPOLlt5GYFn7lDCV2Jw4wIpQLqwboVay

tsingcloud:
  weixin:
    domain: http://17240k68p1.51mypc.cn

jwt:
  token:
    #  token过期时间，单位分钟
    tokenExpireTime: 120
    secretKey: minitoken
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /home/*,/index/*
  # 匹配链接
  urlPatterns: /manager/*
csrf:
  enabled: true
  urlPatterns: /manager/*
  referers: http://localhost/*,127.0.0.1/*,http://124.71.114.133/*,http://17240k68p1.51mypc.cn/*
server:
  port: 80
