server:
  port: 80

file-path: E:\\pics\\spring_boot\\
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:12345/spring-mini?useSSL=false&characterEncoding=utf-8
    username: root
    password: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: com.tsingtec.mini.config.MySQLDialectUTF8
      hibernate.format_sql: false
      hibernate:
        enable_lazy_load_no_trans: true
    open-in-view: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: utf-8
    servlet.content-type: text/html
    cache: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: file:///${file-path},classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/
qiniu:
  accessKey: key
  secretKey: key
  bucket: bucket
  path: path

swagger2:
  enable: true
tsingcloud:
  weixin:
    domain: http://17240k68p1.51mypc.cn
wx:
  miniapp:
    configs:
      - appId: appid
        secret: secret
        token: token
        aesKey: aesKey
        msgDataFormat: JSON
  mp:
    configs:
      - appId: appid
        secret: secret
        token: token
        aesKey: aeskey